"""Normalise the raw research files into the catalogue.

Raw files (catalogue/raw/*.yaml) are the research as collected, one per slice, with
reference vessels nested under each class. The same real vessel is often filed under
several classes, because class schemes overlap (CEMT Va and RWS M8 describe the same
ship). This script makes each Reference Vessel one record, linked to all its classes.

Outputs (generated — edit the raw files, then re-run):
  catalogue/vessel_classes.yaml      one row per Vessel Class, `reference_vessels: [ids]`
  catalogue/reference_vessels.yaml   one row per Reference Vessel, `classes: [ids]`
  catalogue/conflicts.yaml           field values that disagree between raw entries
  catalogue/README.md                human-readable summary table, by region
"""
from __future__ import annotations

import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1] / "catalogue"


def slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")[:60]


def fmt(x) -> str:
    if x is None:
        return "–"
    if isinstance(x, (list, tuple)):
        return "–".join(fmt(i) for i in x) if len(x) == 2 else ", ".join(map(str, x))
    return f"{x:g}" if isinstance(x, (int, float)) else str(x)


def summary(classes: list, vessels: dict) -> str:
    out = ["<!-- GENERATED by tools/build_catalogue.py — do not edit by hand -->",
           "# Vessel class catalogue", "",
           f"{len(classes)} Vessel Classes, {len(vessels)} Reference Vessels. "
           "Source data: `raw/`. Normalised: `vessel_classes.yaml`, `reference_vessels.yaml`.", "",
           "Dimensions in metres, deadweight in tonnes. *Refs* = linked Reference Vessels. "
           "*Conf* = confidence of the class envelope (high = primary source read).", ""]
    order = ["europe-inland", "americas-inland", "asia-inland", "russia-inland",
             "africa-inland", "river-sea", "coastal"]
    regions = sorted({c["region"] for c in classes}, key=lambda r: (order + [r]).index(r))
    for region in regions:
        rows = [c for c in classes if c["region"] == region]
        out += [f"## {region} ({len(rows)})", "",
                "| ID | Family | Formation | Cargo | LOA | Beam | Draught | DWT | Refs | Conf |",
                "|---|---|---|---|---|---|---|---|---|---|"]
        for c in rows:
            cargo = c.get("cargoes") or c.get("cargo_modes")
            out.append("| " + " | ".join([c["id"], c["family"], c["formation"], fmt(cargo),
                fmt(c.get("loa_m")), fmt(c.get("beam_m")), fmt(c.get("draught_m")),
                fmt(c.get("dwt_t")), str(len(c["reference_vessels"])), c["confidence"]]) + " |")
        out.append("")
    return "\n".join(out)


GB_FORMATION = {"dry_bulk_chemical_oil": "motor_vessel", "container": "motor_vessel",
                "ro_ro": "motor_vessel", "sand_self_unloader": "motor_vessel",
                "barge": "pushed_barge"}
GB_CARGO = {"dry_bulk_chemical_oil": ["dry_bulk", "liquid"], "container": ["container"],
            "ro_ro": ["ro_ro"], "sand_self_unloader": ["dry_bulk"], "barge": ["dry_bulk"]}


def from_gb38030(data: dict) -> list:
    """One Vessel Class per GB 38030 standard ship type.

    Part 1 (Changjiang) uses the 2026 edition's envelopes; where a 2019 type has the same category,
    beam and length, its reference deadweight/TEU is carried across and cited. Parts 2-5 use 2019.
    GB 38030 sets beam and length only: draught follows the waterway, so it stays null.
    """
    parts = {p["id"]: p for p in data["parts"]}
    ref_2019 = {}
    for t in parts["GB38030.1-2019"]["tables"]:
        for row in t["rows"]:
            r = dict(zip(t["columns"], row))
            ref_2019[(t["category"], r["boa_m"], r["loa_m"])] = r
    out = []
    for pid in ["GB38030.1-2026", "GB38030.2-2019", "GB38030.3-2019", "GB38030.4-2019",
                "GB38030.5-2019"]:
        part = parts[pid]
        for t in part["tables"]:
            for row in t["rows"]:
                r = dict(zip(t["columns"], row))
                beam = r.get("boa_m", r.get("max_breadth_m"))
                loa = r.get("loa_m", r.get("max_length_m"))
                src = f"{pid} Table {t['table']}"
                old = ref_2019.get((t["category"], beam, loa)) if pid.endswith("2026") else None
                ref = old or r
                if old:
                    src += f"; reference capacity from GB38030.1-2019 type {old['code']}"
                out.append({
                    "id": f"CN-GB38030-{r['code']}", "family": "CN-GB38030",
                    "region": "asia-inland", "waters": "inland",
                    "formation": GB_FORMATION[t["category"]],
                    "cargo_modes": GB_CARGO[t["category"]],
                    "loa_m": loa, "beam_m": beam, "draught_m": None, "air_draft_m": None,
                    "dwt_t": ref.get("ref_dwt_t"), "teu": ref.get("ref_teu"),
                    "n_abreast": 1, "n_in_line": 1, "source": src, "confidence": "high",
                    "notes": "; ".join(x for x in [
                        f"category: {t['category']}", t.get("waters", ""),
                        r.get("applicable_waters_en", ""), r.get("remark_en", ""),
                        "beam/length are maxima (BOA may be up to 2% under, LOA up to 10% under)",
                        "dwt/teu is the standard's REFERENCE value, not a design result"] if x),
                    "reference_vessels": [],
                })
    return out


def working_set(classes: list, scope: dict) -> dict:
    """The classes we prepare, per catalogue/scope.yaml: Hulls get GAs, Formations get arrangements."""
    def keep(c):
        return ((c["family"] in scope["families"] or c["id"] in scope.get("extra_classes", []))
                and all(c.get(k) for k in scope.get("require", []))
                and not any(m in (c.get("notes") or "") for m in scope.get("exclude_notes_matching", [])))
    ins = [c for c in classes if keep(c)]
    hulls = [c["id"] for c in ins if c["formation"] in scope["hull_formations"]]
    return {"hulls": hulls, "formations": [c["id"] for c in ins if c["id"] not in hulls]}


def main() -> None:
    classes, vessels, conflicts, notations = [], {}, [], []
    for path in sorted((ROOT / "raw").glob("*.yaml")):
        data = yaml.safe_load(path.read_text())
        if data.get("standard") == "GB 38030":
            for c in from_gb38030(data):
                c["raw_file"] = path.name
                classes.append(c)
            continue
        notations.extend(data.get("notation_reference") or [])
        for c in data["classes"]:
            c = dict(c)
            c["raw_file"] = path.name
            refs = c.pop("reference_vessels", None) or []
            c["reference_vessels"] = []
            for r in refs:
                vid = slug(r.get("name") or "unnamed")
                v = vessels.setdefault(vid, {"id": vid, "classes": []})
                for k, val in r.items():
                    if val is None:
                        continue
                    if k in v and v[k] != val:
                        conflicts.append({"vessel": vid, "field": k, "kept": v[k],
                                          "other": val, "from_class": c["id"]})
                    else:
                        v.setdefault(k, val)
                v["classes"].append(c["id"])
                c["reference_vessels"].append(vid)
            classes.append(c)
    dump = lambda name, obj: (ROOT / name).write_text(
        "# GENERATED by tools/build_catalogue.py — edit catalogue/raw/, then re-run.\n"
        + yaml.safe_dump(obj, sort_keys=False, allow_unicode=True, width=110))
    dump("vessel_classes.yaml", {"classes": classes, "notation_reference": notations})
    dump("reference_vessels.yaml", {"vessels": list(vessels.values())})
    dump("conflicts.yaml", {"conflicts": conflicts})
    (ROOT / "README.md").write_text(summary(classes, vessels))
    scope = yaml.safe_load((ROOT / "scope.yaml").read_text())
    ws = working_set(classes, scope)
    dump("working_set.yaml", ws)
    print(f"working set: {len(ws['hulls'])} hulls, {len(ws['formations'])} formations")
    print(f"{len(classes)} classes, {len(vessels)} reference vessels, {len(conflicts)} conflicts")


if __name__ == "__main__":
    main()
